### ISSUE TITLE
Boosting a private toot crashes Tootstream

### ISSUE THREAD

**Issue by craigmaloney** [magicalraccoon/tootstream#161]
```
Traceback (most recent call last):
  File "/home/craig/.virtualenvs/tootstream/bin/tootstream", line 9, in <module>
    load_entry_point('tootstream==0.3.2', 'console_scripts', 'tootstream')()
  File "/home/craig/.virtualenvs/tootstream/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/craig/.virtualenvs/tootstream/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/craig/.virtualenvs/tootstream/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/craig/.virtualenvs/tootstream/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/craig/projects/tootstream/src/tootstream/toot.py", line 1915, in main
    cmd_func(mastodon, rest)
  File "/home/craig/projects/tootstream/src/tootstream/toot.py", line 909, in boost
    mastodon.status_reblog(rest)
  File "<decorator-gen-36>", line 2, in status_reblog
  File "/home/craig/.virtualenvs/tootstream/lib/python3.5/site-packages/mastodon/Mastodon.py", line 57, in wrapper
    return function(self, *args, **kwargs)
  File "/home/craig/.virtualenvs/tootstream/lib/python3.5/site-packages/mastodon/Mastodon.py", line 959, in status_reblog
    return self.__api_request('POST', url)
  File "/home/craig/.virtualenvs/tootstream/lib/python3.5/site-packages/mastodon/Mastodon.py", line 1593, in __api_request
    raise MastodonAPIError("Mastodon API returned error: " + response['error'])
mastodon.Mastodon.MastodonAPIError: Mastodon API returned error: This action is not allowed
```

**Comment by craigmaloney** [comment]
Fixed this in develop.
