### ISSUE TITLE
"stream home" immediately crashes

### ISSUE THREAD

**Issue by martensitingale** [magicalraccoon/tootstream#164]
I looked at #163 and it seems to be a different bug. When I try to stream the home timeline on https://anti.energy/ I see the following backtrace (or did prior to the latest commits where I just see `Something went wrong: 'Mastodon' object has no attribute 'stream_user'`):

```
You are connected to https://anti.energy
Enter a command. Use 'help' for a list of commands.


stream[@martensitingale (default)]: stream home
Use ctrl+C to end streaming
Traceback (most recent call last):
  File "toot.py", line 1693, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "toot.py", line 1689, in main
    cmd_func(mastodon, rest)
  File "toot.py", line 1074, in stream
    mastodon.stream_user(toot_listener)
AttributeError: 'Mastodon' object has no attribute 'stream_user'
```

**Comment by nydel** [comment]
note: 70376
  @(user-removed) favorited your status:
  ♺:0 ♥:1 id:23 vis:🌎 via ◆ Tootdon ◆ 2018-01-23 02:06:41 (19 hours ago)
  @(user-removed) you make good points and are clearly thoughtful and think critically. and my further thoughts are - what you say suggests a problem/solution which is better than my simple whinging about progress not being made fast enough. moving from feedlot chicken-nugget tv dinner ft. ambient petroleum byproduct
  toward a more harmonious farming is more concrete. but is it more realistic? without leaving omnivorousness behind, can we supply the demand in a more ethical way, or is it too high?

 note: 70386
Traceback (most recent call last):
  File "/home/nydel/ve/dev/tootstream/bin/tootstream", line 11, in <module>
    load_entry_point('tootstream==0.3.1', 'console_scripts', 'tootstream')()
  File "/home/nydel/ve/dev/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/nydel/ve/dev/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/nydel/ve/dev/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nydel/ve/dev/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/nydel/ve/dev/tootstream/lib/python3.5/site-packages/tootstream-0.3.1-py3.5.egg/tootstream/toot.py", line 1566, in main
  File "/home/nydel/ve/dev/tootstream/lib/python3.5/site-packages/tootstream-0.3.1-py3.5.egg/tootstream/toot.py", line 1015, in note
TypeError: 'NoneType' object is not subscriptable
(tootstream) nydel@foresee:~/ve/dev/tootstream$ 

the very next note that would be displayed is the "blank notification"

**Comment by craigmaloney** [comment]
@nydel Please open a new issue for your issue. I think this is a separate issue. Thanks!

**Comment by craigmaloney** [comment]
@martensitingale Apologies for not seeing this sooner. 

It looks like you have an older version of Mastodon.py installed. You'll need to upgrade to Mastodon.py 1.2.1 in order to use the version of Tootstream that you have installed.

The quickest way to do this would be to create a new virtual environment and re-install Tootstream. The next best way would be to open the virtual environment and type ``pip install --upgrade Mastodon.py``.

Hope this helps!

**Comment by martensitingale** [comment]
Oh, that fixed it. I don't install with virtualenv, I just use my system's packages, which were out of date. Thanks!

**Comment by craigmaloney** [comment]
Awesome! Glad that sorted it out. Thanks for reporting it. :)
