### ISSUE TITLE
Tootstream crashes when faving a deleted toot

### ISSUE THREAD

**Issue by martensitingale** [magicalraccoon/tootstream#178]
There's not much else to say.

```
[@martensitingale (default)]: fav 2302
Traceback (most recent call last):
  File "toot.py", line 1945, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "toot.py", line 1941, in main
    cmd_func(mastodon, rest)
  File "toot.py", line 961, in fav
    mastodon.status_favourite(rest)
  File "<decorator-gen-40>", line 2, in status_favourite
  File "/usr/lib/python3.6/site-packages/mastodon/Mastodon.py", line 57, in wrapper
    return function(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/mastodon/Mastodon.py", line 1004, in status_favourite
    return self.__api_request('POST', url)
  File "/usr/lib/python3.6/site-packages/mastodon/Mastodon.py", line 1613, in __api_request
    error_msg)
mastodon.Mastodon.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Record not found')
```

**Comment by craigmaloney** [comment]
09773300428952175019fac06e2441ce45fa4195 should fix this behavior.

Thanks!
