### ISSUE TITLE
Crash when trying to stream non-existant lists or lists with space " " character in name

### ISSUE THREAD

**Issue by samclotf** [magicalraccoon/tootstream#179]
The command `stream list Mutual Follows`. Double-quotes, single-quotes, and backslashes do not seem to escape the space. However `listhome Mutual Follows` works normally.

```
[@sam (default)]: stream list Mutual Follows
Use ctrl+C to end streaming
Something went wrong: Could not connect to streaming server: Not Found
[@sam (default)]:
```

**Comment by craigmaloney** [comment]
I changed how we're getting the arguments for the lists. Please check
the latest release/0.3.4 branch and verify that what is there is working
for you.

Thanks for finding this, and apologies that it wasn't working for you.

**Comment by samclotf** [comment]
Hi Craig. My mistake, I was using 0.3.3. In 0.3.4, it seems running the stream command with an non-existing stream or a stream with a space crashes the program.

```[@sam (default)]: stream list Mutual Follows
Initializing stream...
Something went wrong: Could not connect to streaming server: Not Found
Traceback (most recent call last):
  File "/home/sam/build/tootstream/bin/tootstream", line 11, in <module>
    load_entry_point('tootstream==0.3.4', 'console_scripts', 'tootstream')()
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/tootstream-0.3.4-py3.5.egg/tootstream/toot.py", line 2104, in main
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/tootstream-0.3.4-py3.5.egg/tootstream/toot.py", line 1279, in stream
UnboundLocalError: local variable 'handle' referenced before assignment```

```[@sam (default)]: stream list DoesNotExist
Initializing stream...
Something went wrong: Could not connect to streaming server: Not Found
Traceback (most recent call last):
  File "/home/sam/build/tootstream/bin/tootstream", line 11, in <module>
    load_entry_point('tootstream==0.3.4', 'console_scripts', 'tootstream')()
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/tootstream-0.3.4-py3.5.egg/tootstream/toot.py", line 2104, in main
  File "/home/sam/build/tootstream/lib/python3.5/site-packages/tootstream-0.3.4-py3.5.egg/tootstream/toot.py", line 1279, in stream
UnboundLocalError: local variable 'handle' referenced before assignment```

**Comment by samclotf** [comment]
I see you fixed this a few hours ago. Closing.

**Comment by craigmaloney** [comment]
Cool. Glad to see it's working. Thanks!
