### ISSUE TITLE
Work with instances other than mastodon.social

### ISSUE THREAD

**Issue by rykermorgan** [magicalraccoon/tootstream#29]
I signed up using the mastodon.xyz instance, and I can't get this CLI started. I think the instance I signed up with might be the problem, but maybe I'm wrong. Below is what comes out when I try to login:

`@ryker:~/tootstream$ python3 tootstream/toot.py
Email used to login: rykermorgan@gmail.com
Password:
Traceback (most recent call last):
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/site-packages/mastodon/Mastodon.py", line 566, in __api_request
    response = response_object.json()
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/site-packages/requests-2.12.3-py3.6.egg/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/site-packages/mastodon/Mastodon.py", line 143, in log_in
    response = self.__api_request('POST', '/oauth/token', params, do_ratelimiting = False)
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/site-packages/mastodon/Mastodon.py", line 568, in __api_request
    raise MastodonAPIError("Could not parse response as JSON, respose code was " + str(response_object.status_code))
mastodon.Mastodon.MastodonAPIError: Could not parse response as JSON, respose code was 200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tootstream/toot.py", line 295, in <module>
    main()
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "tootstream/toot.py", line 271, in main
    login(mastodon, email, password)
  File "tootstream/toot.py", line 39, in login
    to_file = APP_CRED
  File "/Users/ryker.morgan/anaconda3/envs/tootbot/lib/python3.6/site-packages/mastodon/Mastodon.py", line 146, in log_in
    raise MastodonIllegalArgumentError('Invalid user name, password or scopes.')
mastodon.Mastodon.MastodonIllegalArgumentError: Invalid user name, password or scopes.`

**UPDATE: I just saw lines 10-12 in the toot.py showing that only mastodon.social is supported for now.**

**Comment by magicalraccoon** [comment]
Currently only Mastodon.social is supported. I'll try to implement more instance shards soon!

**Comment by rykermorgan** [comment]
I got it working...I just changed the api_base_url in the Mastodon.py package to the shard I'm using. I also generate client_id and access_token separately, directly via api and plugged it back into your program.

I got it working, but obviously its not the best case scenario with the user base and instance base exploding.

**Comment by jidhub** [comment]
Thanks a lot ! Here are my step by step instructions: https://oc.todon.fr/@xdej/48465

**Comment by magicalraccoon** [comment]
Added support in 60a4077f5900e66b7668305456793d78c5220f71
