### ISSUE TITLE
Crash when user attempts to delete an unowned toot

### ISSUE THREAD

**Issue by magicalraccoon** [magicalraccoon/tootstream#89]
I get this error when I try to delete a toot that I didn't post:

`[@raccoon]: delete 19
Traceback (most recent call last):
  File "tootstream/toot.py", line 790, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "tootstream/toot.py", line 786, in main
    cmd_func(mastodon, rest)
  File "tootstream/toot.py", line 472, in delete
    mastodon.status_delete(rest)
  File "/usr/lib/python3.5/site-packages/Mastodon.py-1.0.6-py3.5.egg/mastodon/Mastodon.py", line 449, in status_delete
  File "/usr/lib/python3.5/site-packages/Mastodon.py-1.0.6-py3.5.egg/mastodon/Mastodon.py", line 667, in __api_request
mastodon.Mastodon.MastodonAPIError: Endpoint not found.`

**Comment by magicalraccoon** [comment]
Whoops, this was my fault, I didn't switch back to the virtualenv
